apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: practice
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
          env:
            - name: KIAMOL_SECRET # container 에 전달될 환경 변수명
              valueFrom:
                secretKeyRef: # secret 참조로부터 설정
                  name: sleep-secret-literal # secret 리소스 이름
                  key: secret-key # secret 키 이름

