apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: practice
  name: todo-db
spec:
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: db
          image: postgres:11.6-alpine
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/postgres_password
          volumeMounts:
            - name: secret-password
              mountPath: '/secrets'
              readOnly: true
      volumes:
        - name: secret-password
          secret:
            secretName: todo-db-secret-string # 이 이름으로 정의된 secret 을 가져와
            defaultMode: 0400
            items:
              - key: POSTGRES_PASSWORD # 그 secret 의 이 key 이름
                path: postgres_password # 이 파일명으로 mount
