apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: practice
  name: local-pv
spec:
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  local: # Must set `nodeAffinity` when use local volumes
    path: /volumes/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kiamol
              operator: In
              values:
                - ch05
