apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01 # volume 이름
  namespace: practice
spec:
  capacity:
    storage: 50Mi # volume 용량
  accessModes:
    - ReadWriteOnce # Pod 1개에서만 사용 가능하도록 제한
  nfs:
    server: nfs.my.network # NFS Domain name
    path: /volumes # storage path

