apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-large
  namespace: practice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # 이 요청 용량이 꽉찬 PV 를 발견하지 못한 경우 매핑되지 않고 Pending 상태에 머문다
  storageClassName: ''
