apiVersion: v1
# PV - PVC 는 1:1 대응
kind: PersistentVolumeClaim
metadata:
  namespace: practice
  # Application 은 PVC 로 PV 를 사용한다.
  name: pvc-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
  storageClassName: "" # 스토리지 유형 미지정
