apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      appKind: story
  # pod template
  template:
    metadata:
      labels:
        appKind: story
    spec:
      containers:
        - name: story
          image: milkcoke/kube-volume-app:v1.0.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/story # Container internal path
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {} 의미
          # default value 로 인식하라
          emptyDir: {}

