apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    appKind: story
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # port which container exposed