apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-web
  namespace: practice
data:
  # 이렇게 yaml 에 직접 주입하는 방식이 config map 적용을 한 번에 할 수 있어 편하다.
  # 그렇지 않으면 `kubectl create cm` 을 조지고
  config.json: |-
    {
      "ConfigController": {
        "Enabled": true
      }
    }
  logging.json: |-
    {
      "Logging": {
        "LogLevel": {
            "ToDoList.Pages": "Warning"
          }
        }
    }
  a_c: 'b'
  c: '3a'
# items.key, name 없이 위 파일을 그저 volumeMount 만 하면 4개의 파일이 생성된다.
# 키 개수만큼 config.json, logging.json, a_c, c
