apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: practice
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch04-todo-list
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
