apiVersion: v2
name: pi
description: A pi calculator
type: application
version: 0.1.0
dependencies:
  - name: vweb
    version: 2.0.0
    repository: https://kamol.net
    condition: vweb.enabled
  - name: proxy
    version: 0.1.0
    repository: file://../proxy
    condition: proxy.enabled
