apiVersion: v1
kind: Service

metadata:
  name: sleep-2 # 서비스명: DNS 도메인 주소
  namespace: practice

spec:
  selector:
    app: sleep-2 # `sleep-2 를 label app 값으로 갖는 대상이 타겟
  ports:
    - port: 80 # service 가 노출시키는 포트
      targetPort: 80 # service 가 pod 로 포워딩 시키는 포트
