apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-no-volume
  namespace: practice
spec:
  selector:
    matchLabels:
      app: sleep-no-volume
  template:
    metadata:
      labels:
        app: sleep-no-volume
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
