apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: practice
  name: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
          env:
            - name: SPRING_ACTIVE_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: sleep-spring-env
                  key: SPRING_ACTIVE_PROFILE
          volumeMounts:
            - name: config-file
              mountPath: /config
      volumes:
        - name: config-file
          configMap:
            name: sleep-spring-env
            items:
              - key: config.json
                path: config.json
