apiVersion: v1
kind: Service

metadata:
  name: numbers-api
  namespace: practice
spec:
  # spec 에 selector 가 없는 이유는 대상이 외부 Endpoint 기 때문이다.
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: practice
  name: numbers-api
subsets:
  - addresses:
      - ip: 192.168.123.234
  - ports:
      - port: 80
