apiVersion: v1
kind: Service

metadata:
  name: numbers-web-node
  namespace: practice

spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: numbers-web
  type: NodePort
