apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-web
  namespace: practice
spec:
  selector:
    matchLabels:
      app: numbers-web
  template:
    metadata:
      labels:
        app: numbers-web
    spec:
      containers:
        - name: web
          image: kiamol/ch03-numbers-web
