apiVersion: v1
kind: Service
metadata:
  name: pi-proxy
  namespace: practice
  labels:
    app: pi-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pi-proxy
  type: LoadBalancer
